--03) La empresa quiere conocer el desempeño de sus vendedores, por eso se solicita la venta total en soles y la cantidad de pedidos en un rango determinado de fechas y por sede.
--SHOW: SEDE - LISTAGG(FECHA) - VENDEDOR - TOTAL_SOLES - TOTAL_PEDIDOS
SELECT TBV.DESC1 AS VENDEDOR,
  SED.DESCSEDE AS SEDE,
  LISTAGG (DISTINCT PH.FECHA_PEDIDO, ',') WITHIN GROUP (
    ORDER BY PH.FECHA_PEDIDO
  ) AS FECHAS,
  SUM(MONTO_DESP_BONIF) TOTAL_SOLES,
  COUNT(PH.NRO_PEDIDO) TOTAL_PEDIDOS
FROM SPEDIDO_HEADER PH
  JOIN TABLAS TBV ON TBV.CATEGORIA = '030'
  AND TBV.LLAVE = PH.COD_VENDEDOR
  JOIN TB_SEDE SED ON SED.CODSEDE = PH.CODSEDE
WHERE PH.FECHA_PEDIDO BETWEEN '01-05-2022' AND '05-05-2022'
  AND SED.CODSEDE = '001'
GROUP BY DESC1,
  DESCSEDE;