--01) Un proveedor en especifico quiere conocer la situacion actual de su producto estrella, para recompensar a clientes que hayan adquirido una cantidad fuerte, para ello se requiere la siguiente informacion.
--SHOW SEDE - FECHA - VENDEDOR - CLIENTE - CODIGO - CANTIDAD
SELECT SED.DESCSEDE AS SEDE,
  TO_CHAR(PH.FECHA_PEDIDO) AS FECHA,
  TBV.DESC1 AS VENDEDOR,
  PD.COD_ITEM AS CODIGO,
  SUM(PD.QTY_PEDIDA) CANTIDAD,
  PH.DESC_CLIENTE AS CLIENTE
FROM SPEDIDO_HEADER PH
  JOIN TB_SEDE SED ON SED.CODSEDE = PH.CODSEDE
  JOIN TABLAS TBV ON TBV.CATEGORIA = '030'
  AND TBV.LLAVE = PH.COD_VENDEDOR
  JOIN SPEDIDO_DETALLE PD ON PD.NRO_PEDIDO = PH.NRO_PEDIDO
  AND PD.COMPANIA_VENTA = PH.COMPANIA_VENTA
  JOIN ARTICULOS ART ON ART.COD_ITEM = PD.COD_ITEM
WHERE ART.PROVEEDOR_DEFAULT = '0143'
  AND PD.QTY_PEDIDA > 1000
  AND PD.COD_ITEM = '437389'
  AND PH.FECHA_PEDIDO BETWEEN '01-07-2022' AND '02-08-2022'
GROUP BY SED.DESCSEDE,
  PH.FECHA_PEDIDO,
  TBV.DESC1,
  PD.COD_ITEM,
  PH.DESC_CLIENTE;