--01) Brindar de mayor a menor el monto en soles de pedidos de acuerdo a una fecha y sede en especifico.
--SHOW: SEDE - FECHA - NRO_PEDIDO - MONTO_TOTAL
SELECT SED.DESCSEDE AS SEDE,
  PH.NRO_PEDIDO AS PEDIDO,
  TO_CHAR(PH.FECHA_PEDIDO) AS FECHA,
  PH.MONTO_DESP_BONIF AS MONTO_TOTAL
FROM SYSADM.SPEDIDO_HEADER PH
  INNER JOIN SYSADM.TB_SEDE SED ON SED.CODSEDE = PH.CODSEDE
WHERE PH.FECHA_PEDIDO = '01-10-2022'
  AND PH.CODSEDE = '001'
ORDER BY PH.MONTO_DESP_BONIF DESC;