--02) Brindar la cantidad de clientes atentidos por vendedor de acuerdo a una fecha y sede en especifico.
--SHOW: SEDE - FECHA - CLIENTE - VENDEDOR - CLIENTES_ATENDIDOS 
SELECT SED.DESCSEDE AS SEDE,
  TO_CHAR(PH.FECHA_PEDIDO) AS FECHA,
  TBV.DESC1 AS VENDEDOR,
  COUNT(DISTINCT (PH.COD_CLIENTE)) AS CLIENTES_TOTALES
FROM SPEDIDO_HEADER PH
  INNER JOIN TB_SEDE SED ON SED.CODSEDE = PH.CODSEDE
  INNER JOIN TABLAS TBV ON TBV.CATEGORIA = '030'
  AND TBV.LLAVE = PH.COD_VENDEDOR
WHERE PH.FECHA_PEDIDO = '01-07-2022'
  AND PH.CODSEDE = '001'
GROUP BY FECHA_PEDIDO,
  DESCSEDE,
  DESC1
ORDER BY DESC1;